# **Tarea Nº 1**

Curso:          Fundamentos de Programación en Python para Macroeconomía y Finanzas     
Profesor:       Victor Fuentes Campos     

- Fecha y hora de entrega: Jueves 4 de enero, 11:59pm
- Agregue los nombres de las personas con las que discutió esta tarea: ____ Jakelin Remon ______Patricia Mendoza
- Envíe su tarea haciendo el `push` de su código a su repo en GitHub Classroom: 

# 1. Git


a. Commit, Push, Pull

Instrucciones:
1. Cada miembro del equipo debe clonar el repo de su tarea en su computadora
1. Luego, en el branch master (`main`), el integrante Nº 1 cambia el nombre del archivo `.ipynb` a `tarea_1.ipynb`
1. Usando GitHub Desktop, el integrante Nº 2 notará que hay cambios en el repo. Por lo tanto, hará el `pull` de la nueva versión del repo. Ahora ambos tiene el archivo con el nombre apropiado en sus computadoras

*Este ejercicio se calificará directamente en GitHub*

b. Merge conflicts (opcional)

1. El integrante Nº 1 abre un branch nuevo `merge_conflict_practice_1`. En el archivo `tarea_1.ipynb` reemplazará "Armando Paredes" por su nombre. Luego, hará `commit`y `push` de a GitHub. (En Github Desktop se llama `publish`)
1. El integrante Nº 2 abre un branch nuevo `merge_conflict_practice_2`. En el archivo `tarea_1.ipynb` reemplazará "Armando Paredes" por su nombre. Luego, hará `commit`y `push` de a GitHub. (En Github Desktop se llama `publish`)
1. El integrante Nº 1 hará un `pull request`
1. El integrante Nº 2 hará el `review` del `pull request`, aceptará los cambios de su compañero y hará `merge` del branch al `master`. ¡Listo, completaste tu primer pull request!
1. El integrante Nº 2 hará un `pull request`
1. El integrante Nº 1 hará el `review` del `pull request` y habrá un `merge conflict` poeque ambos están cambiando la misma línea de código. Ajuste el archivo y complete el `merge``
Cambie de roles y fuerce un `merge conflict` con una sección diferente del archivo `tarea_1.ipynb` (Fecha de entrega, nombre del curso, etc.)
1. Explique muy brevemente porque se generó el `merge conflict`

*Respuesta: ______________________________*

# 2. Variables

Considere la siguiente información como punto de partida y complete los espacios en blanco

In [1]:
monthly_savings = 10
num_months = 12
intro = "Hello! How are you?"

a. Calculate year_savings using monthly_savings and num_months


In [3]:
# Calculate the product of monthly_savings and num_months
year_savings = monthly_savings * num_months
year_savings

120

b. Print the type of year_savings

In [4]:
# What do you think the resulting type will be? Find out by printing out the type of year_savings.
print(year_savings)

120


c. Assign sum of intro and intro to doubleintro

In [8]:
# Calculate the sum of intro and intro and store the result in a new variable doubleintro.
doubleintro = intro + intro

d. Print out doubleintro

In [9]:
# Print out doubleintro. Did you expect this?
print(doubleintro)

Hello! How are you?Hello! How are you?


# 3. Lists

Considere la siguiente información como punto de partida y complete los espacios en blanco

In [6]:
import numpy as np
f_list = ["Brazil", np.nan , np.nan, "Austria", "Germany", np.nan, "Pakistan", "np.nan", np.nan ]
text1 = ['My', 'new', 'teacher', 'assistant', 'is', 'so', 'boring.']
p1_list = [ 2 , 3, 4, 5 , 6 ]
values1 = [ 86, 86, 85, 85, 85, 83, 23, 0, 84, 1, 91 ]
last_and_name = [ "CORNEJO SANCHEZ, CHRISTIAN SANTOS", "ORELLANA QUISPE, CRISTIAN NASSER", "MORALES CHOQUEHUANCA, ANGELICA KARINA", "GUIMARAY RIBEYRO, JOSE ROBERTO", "CAMACHO GAVIDIA, ABEL FERNANDO", "TINTAYA ORIHUELA, MEIR ALVARO", "CHAVEZ MARTINEZ, JOSELIN ALEXANDRA", "FIGUEROA MURO, LEONEL ARTURO", "GOMEZ CRIBILLERO, JOSE FELIPE", "PALOMINO SEGUÍN, AFRANIA", "LUZON CUEVA, BIANCA MARIETTE", "SUAÑA ZEGARRA, ADRIAN ANDRE", "SOTO POMACHAGUA, DORKAS YOMIRA JHERMY", "FIORENTINO MARTINEZ, LADY ALY", "LAMA MAVILA, HECTOR ANDRE", "MEZA HINOJO, GUSTAVO", "LOZADA MURILLO, PERSEO MARCELO", "ZAMBRANO JIMENEZ, MIGUEL ALONZO", "JACOBS LUQUE, NICOLAS", "VIDAL VIDAL, ROCIO GABRIELA", "TORRES ANICAMA, JANE CAMILA", "LOPEZ ESTRADA, MARIA ELISA", "BOYCO ORAMS, ALEJANDRO", "DIAZ BERROSPI, KARLINE ROSMELI", "RIEGA ESCALANTE, STEPHY ROSARIO", "LEVANO TORRES, VALERIA CECILIA", "ESQUIVES BRAVO, SEBASTIAN RENATO", "PEREZ GONZALES, JUAN CARLOS", "OTERO MAGUIÑA, MARIANA", "CLAVO CAMPOS, ANDREA BRIZETH", "AGUILAR GARCIA, ERICK JOSUE", "CALDAS VELASQUEZ, JOSUE DANIEL", "SALAS NUÑEZ BORJA, FABIO MANUEL", "PIZARRO VILLANES, FERNANDA NICOLLE", "QUILLATUPA MORALES, ANGELA ADELINA", "HUANCAYA IDONE, CESAR DANTE", "CALVO PORTOCARRERO, GABRIELA ISABEL", "IBAÑEZ ABANTO, ANGEL MAURICIO", "MELÉNDEZ APONTE, JUAN DIEGO", "CRISTIAN SERRANO, ARONE", "HINOJOSA CAHUANA, PERCY ALBERTH", "ANGLAS GARCÍA, KEVIN ARTURO", "ALDAVE ACOSTA, CESAR ERNESTO", "NÚÑEZ HUAMÁN, CÉSAR AGUSTO", "OBREGON HUAMAN, DIANA EDITH", "SOTO PACHERRES, RODRIGO FRANCO", "INGARUCA RIVERA, GRETTEL ALEXANDRA", "ROJAS HUAMAN, ROSA ANGELA", "NEYRA SALAS, DANTE OMAR", "HUERTA ESPINOZA, YAJAIRA ALEXANDRA", "HUANCA MARTINEZ, JORGE ALBERTO", "FLORES CADILLO, ALEXIS" ]
emails = ["cscornejo@pucp.edu.pe", "orellana.cn@pucp.edu.pe", "karina.morales@pucp.edu.pe", "a20083223@pucp.pe", "abel.camacho@pucp.pe", "mtintaya@pucp.edu.pe", "joselin.chavez@pucp.edu.pe", "a20105737@pucp.pe", "jfgomezc@pucp.pe", "afrania.palomino@pucp.pe", "luzon.bianca@pucp.pe", "adrian.suanaz@pucp.pe", "soto.y@pucp.edu.pe", "a20132766@pucp.pe", "andre.lama@pucp.edu.pe", "gustavo.meza@pucp.edu.pe", "pmlozada@pucp.edu.pe", "m.zambranoj@pucp.edu.pe", "nicolas.jacobs@pucp.edu.pe", "gvidal@pucp.edu.pe", "jane.torres@pucp.edu.pe", "m.lopez@pucp.edu.pe", "alejandro.boyco@pucp.edu.pe", "a20167070@pucp.edu.pe", "riega.stephy@pucp.edu.pe", "vlevanot@pucp.edu.pe", "sesquives@pucp.edu.pe", "perez.juanc@pucp.edu.pe", "mariana.otero@pucp.edu.pe", "aclavo@pucp.edu.pe", "a20182474@pucp.edu.pe", "josue.caldas@pucp.edu.pe", "fabio.salas@pucp.edu.pe", "fernanda.pizarro@pucp.edu.pe", "aquillatupa@pucp.pe", "", "", "", "", "", "f0873079@pucp.edu.pe", "", "", "", "", "", "", "", "", "", "", "flores.alexis@pucp.edu.pe", ]

a. Show the indices of the `np.nan`` values in the `f_list` list. We want to see this output: *The indices 1, 2, 5, 8 have np.nan values*. Hint: Use print function and f-strings to insert the indices values.

In [7]:
# Show indices for np.nan values


b. Replicate 4 times the values of the list `p1_list`. We expect an ouput like this: [ 2 , 3, 4, 5, 2 , 3, 4, 5, 2 , 3, 4, 5, 2 , 3, 4, 5]. Hint: Use multiplication function in listsand see the output.

In [8]:
# Replicates p1_list


c. Print the length of `f_list`. **Hint: Length function**

In [9]:
# Lenngth of f_list


d. Print `My new teacher assistant is so boring.` using `text1` list. **Hint: Use the [`join` function](https://stackoverflow.com/questions/493819/why-is-it-string-joinlist-instead-of-list-joinstring)**

In [10]:
# Printing


e. Using `values1`, print <br>
`The max value of values1 is 86 and is located in the 0 index. ` <br>
`The min value of values1 is 0 and is located in the 7 index. ` <br> **Hint: Use the `f-string`, `min`, and `max` functions.**
<br>

In [11]:
# Printing


f. Get two lists: `given_names` and `last_names` using `last_and_name` list. **Hint: Use `map` and `split`.**

In [12]:
# Two lists


g. (Opcional) Give only the last names of students who do not have email. Use the `emails` and `last_names` listt. **Hint: Use `map` and `split`.**

In [13]:
# List of of those who do not have email


# 4.   Tuple


Considere la siguiente información como punto de partida y complete los espacios en blanco

In [1]:
tuple1 = ("Orange", [10, 20, 30], (5, 15, 25))
tuple2 = ([7, 8], [9, 1], [10, 7])

1. Print the first item of the second item of tuple1 object

In [2]:
# Print
print(tuple1)

('Orange', [10, 20, 30], (5, 15, 25))


2. Print the last item of the tuple1 object

In [5]:
print(tuple1[2])


(5, 15, 25)


3. Change the value "orange" for "pink grapefruit". Comment the output

In [9]:
# Change value
tuple1 = ("Pink Grapefruit",) + tuple1[1:]
tuple1

('Pink Grapefruit', [10, 20, 30], (5, 15, 25))

4. Print the length of tuple1

In [10]:
# Print
len(tuple1)

3

5. Sum all the elements of tuple2 and describe your steps and explain each of them. Hint: Use map function.


In [15]:
# Sum all elemenets of tuple2
tuple2
print(tuple2)
# Usar map para aplicar la función sum a cada sublista del tuple
resultado = tuple(map(sum, tuple2))
print(resultado)

([7, 8], [9, 1], [10, 7])
(15, 10, 17)


6. (Opcional) Generate a new tuple object named as tuple3 with the half values of tuple2. This tuple should be similar as tuple2, tuple of lists. Hint: Use map funciont.

In [16]:
print(tuple2)
# Definir una función que realiza la división por un valor específico (por ejemplo, 2)
def dividir_por_dos(sublista):
    return [elemento / 2 for elemento in sublista]

# Usar map para aplicar la función a cada sublista del tuple
tuple3 = tuple(map(dividir_por_dos, tuple2))

# Imprimir el resultado
print(tuple3)


([7, 8], [9, 1], [10, 7])
([3.5, 4.0], [4.5, 0.5], [5.0, 3.5])


# 5. Strings

Considere la siguiente información como punto de partida y complete los espacios en blanco

In [18]:
str1 = 'I am                            too                                                        old'
emails = ["cscornejo@pucp.edu.pe", "orellana.cn@pucp.edu.pe", "karina.morales@pucp.edu.pe", "a20083223@pucp.pe", "abel.camacho@pucp.pe", "mtintaya@pucp.edu.pe", "joselin.chavez@pucp.edu.pe", "a20105737@pucp.pe", "jfgomezc@pucp.pe", "afrania.palomino@pucp.pe", "luzon.bianca@pucp.pe", "adrian.suanaz@pucp.pe", "soto.y@pucp.edu.pe", "a20132766@pucp.pe", "andre.lama@pucp.edu.pe", "gustavo.meza@pucp.edu.pe", "pmlozada@pucp.edu.pe", "m.zambranoj@pucp.edu.pe", "nicolas.jacobs@pucp.edu.pe", "gvidal@pucp.edu.pe", "jane.torres@pucp.edu.pe", "m.lopez@pucp.edu.pe", "alejandro.boyco@pucp.edu.pe", "a20167070@pucp.edu.pe", "riega.stephy@pucp.edu.pe", "vlevanot@pucp.edu.pe", "sesquives@pucp.edu.pe", "perez.juanc@pucp.edu.pe", "mariana.otero@pucp.edu.pe", "aclavo@pucp.edu.pe", "a20182474@pucp.edu.pe", "josue.caldas@pucp.edu.pe", "fabio.salas@pucp.edu.pe", "fernanda.pizarro@pucp.edu.pe", "aquillatupa@pucp.pe"]

1. Drop the duplicated blank spaces in `str1`. Do not use the regular expresions. Do not use the code shown in class. Explain your steps.**Hint: Use `split` method and `join` function.**

In [21]:
# Drop duplicated blank spaces
words = str1.split()
non_empty_words = [word for word in words if word]

2. Get the number of letters in the string .**Hint: Use `len`function.**

In [23]:
# Number of letters
words = str1.split()
non_empty_words = [word for word in words if word]
result_str = ' '.join(non_empty_words)
print(result_str)

I am too old


3. (Optional) Get the number of blank spaces (all of them) in the string .**Hint: Use `len`function.**

In [24]:
# NNumero de espacios vacios
str1 = 'I am                            too                                                        old'

# Contar el numero de espacios vacios
num_blank_spaces = str1.count(' ')

print("Number of blank spaces:", num_blank_spaces)


Number of blank spaces: 85


# 6. NumPy

Considere la siguiente información como punto de partida y complete los espacios en blanco

In [26]:
import numpy as np
prueba1 = np.random.randint(0,10,500)
prueba1


array([8, 9, 2, 5, 5, 8, 8, 0, 3, 5, 8, 6, 6, 0, 0, 1, 0, 5, 7, 4, 4, 1,
       0, 2, 3, 4, 1, 1, 6, 6, 8, 9, 9, 7, 4, 8, 7, 8, 5, 0, 2, 5, 5, 8,
       8, 5, 5, 2, 9, 3, 1, 6, 9, 6, 4, 5, 3, 2, 8, 5, 5, 4, 0, 9, 7, 7,
       4, 7, 3, 7, 2, 8, 8, 1, 2, 7, 9, 3, 7, 4, 6, 1, 3, 9, 6, 8, 5, 5,
       3, 3, 1, 2, 3, 9, 3, 2, 4, 7, 8, 8, 8, 2, 5, 8, 4, 7, 8, 3, 3, 5,
       9, 3, 4, 2, 5, 9, 0, 1, 9, 9, 2, 5, 5, 0, 3, 8, 4, 5, 1, 7, 0, 5,
       7, 2, 1, 2, 2, 8, 1, 2, 9, 7, 1, 1, 7, 6, 3, 4, 0, 7, 9, 1, 0, 7,
       1, 5, 4, 3, 4, 9, 8, 7, 4, 7, 5, 4, 4, 1, 6, 2, 4, 9, 1, 2, 4, 5,
       6, 6, 8, 6, 3, 8, 1, 6, 8, 8, 5, 1, 0, 4, 3, 0, 1, 3, 1, 5, 1, 1,
       5, 7, 5, 0, 6, 8, 5, 9, 8, 3, 1, 2, 2, 2, 9, 9, 6, 2, 4, 2, 8, 9,
       0, 2, 2, 2, 6, 4, 3, 1, 1, 0, 3, 2, 2, 2, 2, 8, 3, 7, 7, 3, 2, 2,
       4, 6, 2, 7, 9, 0, 0, 7, 1, 1, 3, 5, 9, 2, 5, 2, 0, 5, 4, 4, 7, 6,
       0, 7, 1, 1, 4, 3, 4, 0, 1, 9, 9, 6, 7, 9, 8, 0, 1, 8, 2, 6, 7, 4,
       7, 5, 8, 7, 2, 3, 5, 6, 3, 3, 4, 1, 1, 1, 7,

In [27]:
prueba2 = np.arange(50)
np.random.shuffle(prueba2)
prueba2

array([31,  5, 44, 35,  3, 48,  0, 36, 17, 32,  8, 39, 45,  4, 15, 12, 24,
       40, 41, 49, 38, 30, 42, 21, 27, 33, 26,  9, 43, 37, 46, 34, 19, 13,
       29, 14,  1, 22, 18, 10, 47, 11, 28, 20,  6, 16,  2,  7, 23, 25])

a. Find the most frequent value in the prueba1 array?

In [31]:
# Most frequent value
counts = np.bincount(prueba1)
counts
most_frequent_value = np.argmax(counts)
most_frequent_value


3

b. Convert the 1D array prueba2 to a 2D array with 5 rows

In [32]:
# Reshape


# Convert the 1D array to a 2D array with 5 rows
prueba2_2d = np.reshape(prueba2, (5, -1))

# Print the result
print("Original 1D array:")
print(prueba2)
print("\nConverted 2D array with 5 rows:")
print(prueba2_2d)


Original 1D array:
[31  5 44 35  3 48  0 36 17 32  8 39 45  4 15 12 24 40 41 49 38 30 42 21
 27 33 26  9 43 37 46 34 19 13 29 14  1 22 18 10 47 11 28 20  6 16  2  7
 23 25]

Converted 2D array with 5 rows:
[[31  5 44 35  3 48  0 36 17 32]
 [ 8 39 45  4 15 12 24 40 41 49]
 [38 30 42 21 27 33 26  9 43 37]
 [46 34 19 13 29 14  1 22 18 10]
 [47 11 28 20  6 16  2  7 23 25]]
